spring.datasource.url=jdbc:postgresql://localhost:5433/emtlabgroupb
spring.datasource.username=emc
spring.datasource.password=emc

spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true
logging.level.org.flywaydb=DEBUG

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
